name: PHP build

on:
    push:
    pull_request:
    release:
    schedule:
        -   cron: "0 0 1 * *"

jobs:
    run:
        runs-on: ${{ matrix.operating-system }}
        strategy:
            matrix:
                operating-system: [ ubuntu-latest ]
                php-versions: [ '8.1' ]
        name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    coverage: xdebug
                    tools: composer
            -   name: Validate composer.json and composer.lock
                run: composer validate --strict
            -   name: Cache dependencies
                id: cache-composer
                uses: actions/cache@v3
                env:
                    cache-name: cache-vendor
                with:
                    path: vendor
                    key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-build-${{ env.cache-name }}-
                        ${{ runner.os }}-build-
                        ${{ runner.os }}-

            -   if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
                name: Composer info
                continue-on-error: true
                run: composer info
            -   name: Install dependencies
                run: composer install --prefer-source
            -   name: Checks
                run: composer ci:pack
