name: PHP build

on:
    push:
    pull_request:
    release:
    schedule:
        -   cron: "0 0 1 * *"

jobs:
    run:
        runs-on: ${{ matrix.operating-system }}
        strategy:
            matrix:
                operating-system: [ ubuntu-latest ]
                php-versions: [ '8.1' ]
        name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    coverage: xdebug
                    tools: composer
            -   name: "Validate composer.json and composer.lock"
                run: "composer validate --strict"
            -   name: "Determine composer cache directory"
                id: "determine-composer-cache-directory"
                run: "echo \"::set-output name=directory::$(composer config cache-dir)\""
            -   name: "Cache dependencies installed with composer"
                uses: "actions/cache@v2.0.0"
                with:
                    path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
                    key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
                    restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"
            -   name: Install package
                run: |
                    composer install --prefer-source
            -   name: Checks
                run: |
                    composer ci:pack
